-- MySQL Script generated by MySQL Workbench
-- Mon May  8 10:50:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dost
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dost` ;

-- -----------------------------------------------------
-- Schema dost
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dost` DEFAULT CHARACTER SET utf8mb4 ;
USE `dost` ;

-- -----------------------------------------------------
-- Table `dost`.`dost_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`dost_admin` (
  `admin_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`application` (
  `application_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_id` INT UNSIGNED NOT NULL,
  `submitted` DATETIME NOT NULL,
  `scholarship_type` ENUM('RA2067', 'RA7687') NOT NULL,
  `status` ENUM('APPROVED', 'DENIED') NOT NULL,
  PRIMARY KEY (`application_id`),
  INDEX `admin_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_application_admin`
    FOREIGN KEY (`admin_id`)
    REFERENCES `dost`.`dost_admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`address` (
  `address_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `purok` VARCHAR(256) NOT NULL,
  `street` VARCHAR(256) NULL DEFAULT NULL,
  `barangay` VARCHAR(256) NOT NULL,
  `city` VARCHAR(256) NOT NULL,
  `zipcode` VARCHAR(256) NULL DEFAULT NULL,
  `province` VARCHAR(256) NOT NULL,
  `region` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`applicant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`applicant` (
  `applicant_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_id` INT UNSIGNED NOT NULL,
  `home_address_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex_at_birth` ENUM('MALE', 'FEMALE') NULL DEFAULT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `family_annual_income` INT NOT NULL,
  PRIMARY KEY (`applicant_id`),
  INDEX `application_idx` (`application_id` ASC) VISIBLE,
  INDEX `adress_idx` (`home_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_applicant_application`
    FOREIGN KEY (`application_id`)
    REFERENCES `dost`.`application` (`application_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicant_address`
    FOREIGN KEY (`home_address_id`)
    REFERENCES `dost`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`school` (
  `school_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `office_address_id` INT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(256) NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`school_id`),
  INDEX `address_idx` (`office_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_school_address`
    FOREIGN KEY (`office_address_id`)
    REFERENCES `dost`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`registrar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`registrar` (
  `registrar_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`registrar_id`),
  INDEX `school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `fk_registrar_school`
    FOREIGN KEY (`school_id`)
    REFERENCES `dost`.`school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`course` (
  `course_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`scholarship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`scholarship` (
  `scholarship_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('RA2067', 'RA7687') NOT NULL,
  `status` ENUM('ACTIVE', 'ON_LEAVE', 'TERMINATED') NOT NULL DEFAULT 'ACTIVE',
  `award_year` YEAR NOT NULL,
  `end_year` YEAR NOT NULL,
  PRIMARY KEY (`scholarship_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`scholar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`scholar` (
  `scholar_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scholarship_id` INT UNSIGNED NOT NULL,
  `school_id` INT UNSIGNED NOT NULL,
  `course_id` INT UNSIGNED NOT NULL,
  `home_address_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex_at_birth` ENUM('MALE', 'FEMALE') NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `year_level` TINYINT NOT NULL,
  PRIMARY KEY (`scholar_id`),
  INDEX `school_idx` (`school_id` ASC) VISIBLE,
  INDEX `course_idx` (`course_id` ASC) VISIBLE,
  INDEX `scholarship_idx` (`scholarship_id` ASC) VISIBLE,
  INDEX `address_idx` (`home_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_scholar_school`
    FOREIGN KEY (`school_id`)
    REFERENCES `dost`.`school` (`school_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scholar_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `dost`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scholar_scholarship`
    FOREIGN KEY (`scholarship_id`)
    REFERENCES `dost`.`scholarship` (`scholarship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scholar_address`
    FOREIGN KEY (`home_address_id`)
    REFERENCES `dost`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`certificate_of_grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`certificate_of_grades` (
  `certificate_id'` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `scholar_id` INT UNSIGNED NOT NULL,
  `registrar_id` INT UNSIGNED NOT NULL,
  `admin_id` INT UNSIGNED NOT NULL,
  `year` TINYINT NOT NULL,
  `semester` TINYINT NOT NULL,
  PRIMARY KEY (`certificate_id'`),
  INDEX `student_idx` (`scholar_id` ASC) VISIBLE,
  INDEX `registrar_idx` (`registrar_id` ASC) VISIBLE,
  INDEX `admin_idx` (`admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_cog_student`
    FOREIGN KEY (`scholar_id`)
    REFERENCES `dost`.`scholar` (`scholar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cog_registrar`
    FOREIGN KEY (`registrar_id`)
    REFERENCES `dost`.`registrar` (`registrar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cog_admin`
    FOREIGN KEY (`admin_id`)
    REFERENCES `dost`.`dost_admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dost`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dost`.`subject` (
  `subject_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `unit` TINYINT NOT NULL,
  `description` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_subject_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `dost`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
